import { SUBSET_DEFS } from './subsetDefs.js'
import {
  generateBuildDimensionProlog,
  generateBuildDimensionData,
  generateBuildDimensionEpilog,
} from './computeDimension.js'

export {
  generateBuildDimensionProlog,
  generateBuildDimensionData,
  generateBuildDimensionEpilog,
}

// ═══════════════════════════════════════════════════════════════════════
//  BUILD PERIOD DIMENSION TI
//  Creates dimension, attributes, elements, edges, and attribute values.
//  Parameters: pFirstFY, pLastFY, pFYStartM, pCurrentPeriod
// ═══════════════════════════════════════════════════════════════════════

export function generateBuildDimensionSections(params, selectedSubsets = []) {
  return {
    prolog:   generateBuildDimensionProlog(params, selectedSubsets),
    metadata: '',
    data:     generateBuildDimensionData(params),
    epilog:   generateBuildDimensionEpilog(params, selectedSubsets),
    parameters: [
      { Name: 'pFirstFY',    Type: 'Numeric', Value: params.firstFY,     Prompt: 'First Fiscal Year (e.g. FY2025)' },
      { Name: 'pLastFY',     Type: 'Numeric', Value: params.lastFY,      Prompt: 'Last Fiscal Year (e.g. FY2035)' },
      { Name: 'pFYStartM',   Type: 'Numeric', Value: params.fyStartMonth, Prompt: 'FY start month (1-12)' },
      { Name: 'pCurrentPeriod', Type: 'String', Value: params.defaultCurrentPeriod || '', Prompt: 'REQUIRED — Current period e.g. 2027-05' },
    ],
  }
}

export function generateBuildDimensionTI(params, selectedSubsets = []) {
  const prolog = generateBuildDimensionProlog(params, selectedSubsets)
  const data   = generateBuildDimensionData(params)
  const epilog = generateBuildDimensionEpilog(params, selectedSubsets)
  return [
    `#####################################################`,
    `# Build Period Dimension — ${params.dimensionName}`,
    `# Generated by TM1 IDE Period Builder`,
    `# Params: pFirstFY, pLastFY, pFYStartM`,
    `#####################################################`,
    ``,
    `# ── PROLOG ──`, prolog,
    ``,
    `# ── DATA ──`, data,
    ``,
    `# ── EPILOG ──`, epilog,
  ].join('\n')
}

// ═══════════════════════════════════════════════════════════════════════
//  REFRESH SUBSETS TI
//  Rebuilds all selected public subsets by walking the dimension.
//  Uses existing YTD/YTG/LTD consolidations for efficient subset building.
//  Parameters: pDimension, pCurrentPeriod, pFYStartM
// ═══════════════════════════════════════════════════════════════════════

function buildRefreshProlog(params, selectedSubsets, subsetPrefix) {
  const { dimensionName, fyStartMonth } = params
  const pfx = subsetPrefix ? subsetPrefix + ' ' : ''
  const needsCurrent = selectedSubsets.some(id => {
    const def = SUBSET_DEFS.find(d => d.id === id)
    return def?.requiresCurrent
  })

  const out = []

  // ── Header ──
  out.push(`# ═══════════════════════════════════════════════════════════════`)
  out.push(`# Period Dimension Subset Rebuild`)
  out.push(`# ═══════════════════════════════════════════════════════════════`)
  out.push(`# Dimension: ${dimensionName}`)
  out.push(`# Purpose : Destroys and recreates all selected public subsets`)
  out.push(`# Input   : pCurrentPeriod — the month to use as reference`)
  out.push(`# Output  : Rebuild subsets in the target dimension`)
  out.push(`# ═══════════════════════════════════════════════════════════════`)
  out.push(``)
  out.push(`# vCount = total number of elements in the dimension`)
  out.push(`vCount = DIMSIZ(pDimension);`)
  out.push(``)

  if (needsCurrent) {
    out.push(`# ─────────────────────────────────────────────`)
    out.push(`# Validate & Resolve Current Period`)
    out.push(`# Reads pCurrentPeriod parameter (e.g. '2027-04')`)
    out.push(`# Extracts: FY name, prior FY/period`)
    out.push(`# Also computes YTD/YTG/LTD consolidation names`)
    out.push(`# ─────────────────────────────────────────────`)
    out.push(`# ── Validate Current Period ──`)
    out.push(`# Check: parameter must not be empty`)
    out.push(`IF(pCurrentPeriod @= '');`)
    out.push(`  ItemReject('pCurrentPeriod is required — set a period e.g. 2027-05');`)
    out.push(`  ProcessQuit;`)
    out.push(`ENDIF;`)
    out.push(`IF(DIMIX(pDimension, pCurrentPeriod) = 0);`)
    out.push(`  ItemReject('Period not found in dimension: ' | pCurrentPeriod);`)
    out.push(`  ProcessQuit;`)
    out.push(`ENDIF;`)
    out.push(``)

    // Read attribute values from the current period element
    out.push(`# Read current period attribute values`)
    out.push(`# ── Read attribute values from current period element ──`)
    out.push(`# sCurrentFY = Fin Year attribute of current period (e.g. 'FY2027')`)
    out.push(`sCurrentFY = ATTRS(pDimension, pCurrentPeriod, 'Fin Year');`)
    out.push(`# sPriorPeriod = element name of the month before current`)
    out.push(`sPriorPeriod = ATTRS(pDimension, pCurrentPeriod, 'Previous Period');`)
    out.push(`# sYTD = name of the YTD consolidation for current period (e.g. 'YTD FY2027 P01')`)
    out.push(`sYTD = ATTRS(pDimension, pCurrentPeriod, 'YTD');`)
    out.push(`# sYTG = name of the YTG consolidation for current period`)
    out.push(`sYTG = ATTRS(pDimension, pCurrentPeriod, 'YTG');`)
    out.push(`# sLTD = name of the LTD consolidation for current period`)
    out.push(`sLTD = ATTRS(pDimension, pCurrentPeriod, 'LTD');`)

    // Extract FY year from Fin Year attribute (e.g. 'FY2027' → 2027)
    out.push(`# Extract numeric FY year from attribute`)
    out.push(`# ── Extract FY year number and compute prior/next FY names ──`)
    out.push(`# Extract the FY year number from 'FY2027' → 2027`)
    out.push(`nFY = StringToNumber(SUBST(sCurrentFY, 3, 4));`)
    out.push(`# Prior FY name (e.g. 'FY2026')`)
    out.push(`sPriorFY = 'FY' | NumberToString(nFY - 1);`)
    out.push(`# Next FY name (e.g. 'FY2028')`)
    out.push(`sNextFY  = 'FY' | NumberToString(nFY + 1);`)
    out.push(`# OBL element name (e.g. '2027 OBL')`)
    out.push(`sOBL = NumberToString(nFY) | ' OBL';`)
    out.push(``)

    if (selectedSubsets.includes('prior-ytd') || selectedSubsets.includes('prior-ytg') || selectedSubsets.includes('prior-ltd')) {
      out.push(`# ─────────────────────────────────────────────`)
      out.push(`# Compute Prior-Year consolidation names`)
      out.push(`# Uses same calendar-month / fiscal-period formula`)
      out.push(`# as the Build Dimension TI`)
      out.push(`# ─────────────────────────────────────────────`)
      out.push(`nCalMonth = ATTRN(pDimension, pCurrentPeriod, 'Calendar Month');`)
      out.push(`nPriorFis = MOD(nCalMonth - pFYStartM + 12, 12) + 1;`)
      out.push(`sPriorYTD = 'YTD FY' | NumberToString(nFY - 1) | ' P' | IF(nPriorFis < 10, '0' | NumberToString(nPriorFis), NumberToString(nPriorFis));`)
      out.push(`sPriorYTG = 'YTG FY' | NumberToString(nFY - 1) | ' P' | IF(nPriorFis < 10, '0' | NumberToString(nPriorFis), NumberToString(nPriorFis));`)
      out.push(`sPriorLTD = 'LTD FY' | NumberToString(nFY - 1) | ' P' | IF(nPriorFis < 10, '0' | NumberToString(nPriorFis), NumberToString(nPriorFis));`)
      out.push(``)
    }
  }

  // Helper: create a public subset (destroy if exists)
  const writeSubset = (label) => {
    const name = pfx + label
    out.push(`# ══════ Subset: ${name} ══════`)
    out.push(`IF(SubsetExists(pDimension, '${name}') = 1);`)
    out.push(`  SubsetDestroy(pDimension, '${name}');`)
    out.push(`ENDIF;`)
    out.push(`SubsetCreate(pDimension, '${name}');`)
  }

  // Helper: add a single element to the current subset
  const addEl = (name, elExpr) => {
    out.push(`IF(DIMIX(pDimension, ${elExpr}) > 0);`)
    out.push(`  SubsetElementInsert(pDimension, '${name}', ${elExpr}, nPos);`)
    out.push(`  nPos = nPos + 1;`)
    out.push(`ENDIF;`)
  }

  // Helper: add a consolidation and all its direct children to the subset
  const addChildren = (name, parentExpr) => {
    out.push(`IF(DIMIX(pDimension, ${parentExpr}) > 0);`)
    out.push(`  # Add parent consolidation itself`)
    out.push(`  SubsetElementInsert(pDimension, '${name}', ${parentExpr}, nPos);`)
    out.push(`  nPos = nPos + 1;`)
    out.push(`  # Add all child elements`)
    out.push(`  nChild = 1;`)
    out.push(`  nChildCount = ELCOMPN(pDimension, ${parentExpr});`)
    out.push(`  WHILE(nChild <= nChildCount);`)
    out.push(`    sChild = ELCOMP(pDimension, ${parentExpr}, nChild);`)
    out.push(`    SubsetElementInsert(pDimension, '${name}', sChild, nPos);`)
    out.push(`    nPos = nPos + 1;`)
    out.push(`    nChild = nChild + 1;`)
    out.push(`  END;`)
    out.push(`ENDIF;`)
  }

  // ── Build each selected subset ──
  for (const id of selectedSubsets) {
    const name = pfx + (() => {
      switch (id) {
        case 'all-periods': return 'All Periods'
        case 'all-fy':      return 'All FY'
        case 'current-period': return 'Current Period'
        case 'prior-period':   return 'Prior Period'
        case 'current-fy':     return 'Current FY'
        case 'prior-fy':       return 'Prior FY'
        case 'next-fy':        return 'Next FY'
        case 'ytd':            return 'YTD'
        case 'ytg':            return 'YTG'
        case 'ltd':            return 'LTD'
        case 'prior-ytd':      return 'Prior YTD'
        case 'prior-ytg':      return 'Prior YTG'
        case 'prior-ltd':      return 'Prior LTD'
        case 'rolling-12':     return 'Rolling 12'
        case 'rolling-6':      return 'Rolling 6'
        case 'rolling-3':      return 'Rolling 3'
      }
    })()

    writeSubset(name)
    out.push(`nPos = 1;`)

    switch (id) {
      case 'all-periods':
        out.push(`# Walk entire dimension, include leaf elements (exclude OBL)`)
        out.push(`vIdx = 1;`)
        out.push(`WHILE(vIdx <= vCount);`)
        out.push(`  sEl = DIMNM(pDimension, vIdx);`)
        out.push(`  IF(ElementLevel(pDimension, pDimension, sEl) = 0);`)
        out.push(`    IF(ATTRS(pDimension, sEl, 'Period Type') @<> 'OBL');`)
        out.push(`      SubsetElementInsert(pDimension, '${name}', sEl, nPos);`)
        out.push(`      nPos = nPos + 1;`)
        out.push(`    ENDIF;`)
        out.push(`  ENDIF;`)
        out.push(`  vIdx = vIdx + 1;`)
        out.push(`END;`)
        break

      case 'all-fy':
        out.push(`# Walk dimension, include only FY consolidations (names starting with 'FY')`)
        out.push(`vIdx = 1;`)
        out.push(`WHILE(vIdx <= vCount);`)
        out.push(`  sEl = DIMNM(pDimension, vIdx);`)
        out.push(`  IF(ElementLevel(pDimension, pDimension, sEl) > 0);`)
        out.push(`    IF(SUBST(sEl, 1, 2) @= 'FY');`)
        out.push(`      SubsetElementInsert(pDimension, '${name}', sEl, nPos);`)
        out.push(`      nPos = nPos + 1;`)
        out.push(`    ENDIF;`)
        out.push(`  ENDIF;`)
        out.push(`  vIdx = vIdx + 1;`)
        out.push(`END;`)
        break

      case 'current-period':
        out.push(`# Single element: the current period`)
        addEl(name, `pCurrentPeriod`); break

      case 'prior-period':
        out.push(`# Single element: the period before current`)
        addEl(name, `sPriorPeriod`); break

      case 'current-fy':
        out.push(`# FY consolidation + all 12 months`)
        addChildren(name, `sCurrentFY`); break

      case 'prior-fy':
        out.push(`# Prior FY consolidation + all 12 months`)
        addChildren(name, `sPriorFY`); break

      case 'next-fy':
        out.push(`# Next FY consolidation + all 12 months`)
        addChildren(name, `sNextFY`); break

      case 'ytd':
        out.push(`# YTD consolidation + its children (months Apr through current)`)
        addChildren(name, `sYTD`); break

      case 'ytg':
        out.push(`# YTG consolidation + its children (remaining months in FY)`)
        addChildren(name, `sYTG`); break

      case 'ltd':
        out.push(`# LTD = OBL + YTD consolidation + all month children (grandchildren)`)
        out.push(`IF(DIMIX(pDimension, sLTD) > 0);`)
        out.push(`  # Add LTD parent`)
        out.push(`  SubsetElementInsert(pDimension, '${name}', sLTD, nPos);`)
        out.push(`  nPos = nPos + 1;`)
        out.push(`  # Add direct children of LTD (OBL + YTD)`)
        out.push(`  nChild = 1;`)
        out.push(`  nChildCount = ELCOMPN(pDimension, sLTD);`)
        out.push(`  WHILE(nChild <= nChildCount);`)
        out.push(`    sChild = ELCOMP(pDimension, sLTD, nChild);`)
        out.push(`    SubsetElementInsert(pDimension, '${name}', sChild, nPos);`)
        out.push(`    nPos = nPos + 1;`)
        out.push(`    # For YTD child, also add its children (grandchildren = months)`)
        out.push(`    IF(sChild @<> sOBL);`)
        out.push(`      nGrand = 1;`)
        out.push(`      nGrandCount = ELCOMPN(pDimension, sChild);`)
        out.push(`      WHILE(nGrand <= nGrandCount);`)
        out.push(`        sGrand = ELCOMP(pDimension, sChild, nGrand);`)
        out.push(`        SubsetElementInsert(pDimension, '${name}', sGrand, nPos);`)
        out.push(`        nPos = nPos + 1;`)
        out.push(`        nGrand = nGrand + 1;`)
        out.push(`      END;`)
        out.push(`    ENDIF;`)
        out.push(`    nChild = nChild + 1;`)
        out.push(`  END;`)
        out.push(`ENDIF;`)
        break

      case 'prior-ytd':
        addChildren(name, `sPriorYTD`); break
      case 'prior-ytg':
        addChildren(name, `sPriorYTG`); break
      case 'prior-ltd':
        out.push(`# Prior LTD: same structure as LTD but for prior FY`)
        out.push(`sPriorOBL = NumberToString(nFY - 1) | ' OBL';`)
        out.push(`IF(DIMIX(pDimension, sPriorLTD) > 0);`)
        out.push(`  SubsetElementInsert(pDimension, '${name}', sPriorLTD, nPos);`)
        out.push(`  nPos = nPos + 1;`)
        out.push(`  nChild = 1;`)
        out.push(`  nChildCount = ELCOMPN(pDimension, sPriorLTD);`)
        out.push(`  WHILE(nChild <= nChildCount);`)
        out.push(`    sChild = ELCOMP(pDimension, sPriorLTD, nChild);`)
        out.push(`    SubsetElementInsert(pDimension, '${name}', sChild, nPos);`)
        out.push(`    nPos = nPos + 1;`)
        out.push(`    IF(sChild @<> sPriorOBL);`)
        out.push(`      nGrand = 1;`)
        out.push(`      nGrandCount = ELCOMPN(pDimension, sChild);`)
        out.push(`      WHILE(nGrand <= nGrandCount);`)
        out.push(`        sGrand = ELCOMP(pDimension, sChild, nGrand);`)
        out.push(`        SubsetElementInsert(pDimension, '${name}', sGrand, nPos);`)
        out.push(`        nPos = nPos + 1;`)
        out.push(`        nGrand = nGrand + 1;`)
        out.push(`      END;`)
        out.push(`    ENDIF;`)
        out.push(`    nChild = nChild + 1;`)
        out.push(`  END;`)
        out.push(`ENDIF;`)
        break

      case 'rolling-12':
        out.push(`# Rolling 12 subset: children of the 'Rolling 12' consolidation (built by dimension)`)
        addChildren(name, "'Rolling 12'"); break

      case 'rolling-6':
        out.push(`# Rolling 6 subset: children of the 'Rolling 6' consolidation`)
        addChildren(name, "'Rolling 6'"); break

      case 'rolling-3':
        out.push(`# Rolling 3 subset: children of the 'Rolling 3' consolidation`)
        addChildren(name, "'Rolling 3'"); break
    }
    out.push(``)
  }

  return out.join('\n')
}

export function generateRefreshSubsetsSections(params, selectedSubsets, subsetPrefix) {
  return {
    prolog:   buildRefreshProlog(params, selectedSubsets, subsetPrefix),
    metadata: '',
    data:     '',
    epilog:   '',
    parameters: [
      { Name: 'pDimension', Type: 'String', Value: params.dimensionName, Prompt: 'Dimension name' },
      { Name: 'pCurrentPeriod', Type: 'String', Value: params.defaultCurrentPeriod || '', Prompt: 'REQUIRED — Current period e.g. 2027-05' },
      { Name: 'pFYStartM', Type: 'Numeric', Value: params.fyStartMonth, Prompt: 'FY start month (1-12)' },
    ],
  }
}

export function generateRefreshSubsetsTI(params, selectedSubsets, subsetPrefix) {
  return [
    `#####################################################`,
    `# Refresh Subsets — ${params.dimensionName}`,
    `# Generated by TM1 IDE Period Builder`,
    `# Schedule: run monthly after Rollover TI`,
    `#####################################################`,
    ``,
    buildRefreshProlog(params, selectedSubsets, subsetPrefix),
  ].join('\n')
}

// ═══════════════════════════════════════════════════════════════════════
//  ROLLOVER TI
//  Advances the Is Current Period flag by one month (or to user-specified)
//  Parameters: pDimension, pCurrentPeriod, pPeriod (optional)
// ═══════════════════════════════════════════════════════════════════════

function buildRolloverProlog(dimensionName, fyStartMonth = 1) {
  const out = []
  out.push(`# ═══════════════════════════════════════════════════════════════`)
  out.push(`# ${dimensionName}.Rollover`)
  out.push(`#`)
  out.push(`# Purpose : Advances the 'Is Current Period' flag by one month`)
  out.push(`#           (or to any chosen period if pPeriod is supplied).`)
  out.push(`#           Automatically triggers .Refresh Subsets afterwards.`)
  out.push(`#`)
  out.push(`# Typical use: Monthly chore scheduled for the 1st of each month`)
  out.push(`#            with pPeriod left blank (auto-advance mode).`)
  out.push(`# ═══════════════════════════════════════════════════════════════`)
  out.push(``)
  out.push(`vCount = DIMSIZ(pDimension);`)
  out.push(``)

  out.push(`# ─────────────────────────────────────────────`)
  out.push(`# 1. Validate input parameters`)
  out.push(`# ─────────────────────────────────────────────`)
  out.push(`IF(pCurrentPeriod @= '');`)
  out.push(`  ItemReject('pCurrentPeriod is required — set a period e.g. 2027-05');`)
  out.push(`  ProcessQuit;`)
  out.push(`ENDIF;`)
  out.push(`IF(DIMIX(pDimension, pCurrentPeriod) = 0);`)
  out.push(`  ItemReject('Period not found in dimension: ' | pCurrentPeriod);`)
  out.push(`  ProcessQuit;`)
  out.push(`ENDIF;`)
  out.push(``)

  out.push(`# ─────────────────────────────────────────────`)
  out.push(`# Advance Is Current Period flag`)
  out.push(`# pPeriod blank → auto-advance one month`)
  out.push(`# pPeriod set → jump to specific period`)
  out.push(`# ─────────────────────────────────────────────`)
  out.push(`sOldPeriod = pCurrentPeriod;`)
  out.push(``)
  out.push(`IF(pPeriod @= '');`)
  out.push(`  sNewPeriod = ATTRS(pDimension, sOldPeriod, 'Next Period');`)
  out.push(`ELSE;`)
  out.push(`  sNewPeriod = pPeriod;`)
  out.push(`ENDIF;`)
  out.push(``)
  out.push(`IF(sNewPeriod @= '');`)
  out.push(`  ProcessQuit;`)
  out.push(`ENDIF;`)
  out.push(``)
  out.push(`# Clear old flag, set new flag`)
  out.push(`IF(sOldPeriod @<> '');`)
  out.push(`  AttrPutS('', pDimension, sOldPeriod, 'Is Current Period');`)
  out.push(`ENDIF;`)
  out.push(`AttrPutS('Y', pDimension, sNewPeriod, 'Is Current Period');`)
  out.push(``)
  out.push(`# Rebuild subsets using new current period`)
  out.push(`IF(sOldPeriod @<> '');`)
  out.push(`  # Pass pFYStartM so the Refresh Subsets process uses the same fiscal year definition`)
  out.push(`  ExecuteProcess(pDimension | '.Refresh Subsets',`)
  out.push(`                 'pCurrentPeriod', sNewPeriod,`)
  out.push(`                 'pFYStartM', NumberToString(pFYStartM));`)
  out.push(`ENDIF;`)
  return out.join('\n')
}

export function generateRolloverSections(params) {
  return {
    prolog:   buildRolloverProlog(params.dimensionName, params.fyStartMonth),
    metadata: '',
    data:     '',
    epilog:   '',
    parameters: [
      { Name: 'pDimension', Type: 'String', Value: params.dimensionName, Prompt: 'Dimension name' },
      { Name: 'pCurrentPeriod', Type: 'String', Value: params.defaultCurrentPeriod || '', Prompt: 'REQUIRED — Current period e.g. 2027-05' },
      { Name: 'pPeriod', Type: 'String', Value: '', Prompt: 'Period to set as current (blank = auto-advance using Next Period)' },
      { Name: 'pFYStartM', Type: 'Numeric', Value: params.fyStartMonth, Prompt: 'FY start month (1-12) — passed to Refresh Subsets' },
    ],
  }
}

export function generateRolloverTI(params) {
  return [
    `#####################################################`,
    `# ${params.dimensionName}.Rollover`,
    `# Generated by TM1 IDE Period Builder`,
    `#`,
    `# Purpose : Advances the 'Is Current Period' flag by one month`,
    `#           (or to a specific period if pPeriod is supplied).`,
    `#           Then triggers .Refresh Subsets for the new current period.`,
    `#`,
    `# Parameters:`,
    `#   pCurrentPeriod  (required) — Current period element name (e.g. 2027-05)`,
    `#   pPeriod         (optional) — Target period. Blank = auto-advance using Next Period attribute`,
    `#   pFYStartM       (optional) — Fiscal year start month (passed to Refresh Subsets)`,
    `#`,
    `# Recommended schedule: Monthly chore on the 1st of each month`,
    `# with pPeriod left blank.`,
    `#####################################################`,
    ``,
    buildRolloverProlog(params.dimensionName, params.fyStartMonth),
  ].join('\n')
}
