import { SUBSET_DEFS } from './subsetDefs.js'

const ATTR_TYPES = {
  'Period Start Serial':  'Numeric',
  'Period End Serial':    'Numeric',
  'Calendar Year':        'Numeric',
  'Calendar Month':       'Numeric',
  'Days in Period':       'Numeric',
  'Fin Year':             'String',
  'First Period':         'String',
  'Last Period':          'String',
  'Previous Period':      'String',
  'Next Period':          'String',
  'Caption':              'Alias',
  'Long Name':            'String',
  'Is Current Period':    'String',
}

// ── BuildDimension ────────────────────────────────────────────────────────────

function buildProlog(dimensionName, usedAttrs) {
  const out = []
  out.push(`pDimension = '${dimensionName}';`)
  return out.join('\n')
}

function buildMetadata(elements, edges) {
  const out = []
  const consolidated = elements.filter(e => e.type === 'C')
  const numeric      = elements.filter(e => e.type === 'N')

  out.push(`# Consolidated members`)
  for (const { name } of consolidated) {
    out.push(`IF(DIMIX(pDimension, '${name}') = 0);`)
    out.push(`  DimensionElementInsert(pDimension, '', '${name}', 'C');`)
    out.push(`ENDIF;`)
  }
  out.push(``)
  out.push(`# Leaf month members`)
  for (const { name } of numeric) {
    out.push(`IF(DIMIX(pDimension, '${name}') = 0);`)
    out.push(`  DimensionElementInsert(pDimension, '', '${name}', 'N');`)
    out.push(`ENDIF;`)
  }
  out.push(``)
  out.push(`# Hierarchy edges`)
  for (const { parent, child, weight } of edges) {
    out.push(`DimensionElementComponentAdd(pDimension, '${parent}', '${child}', ${weight});`)
  }
  return out.join('\n')
}

function buildEpilog(attributes) {
  const out = []
  out.push(`# Attribute values`)
  for (const [elemName, attrs] of Object.entries(attributes)) {
    const pairs = Object.entries(attrs).filter(([, v]) => v !== '' && v != null)
    if (pairs.length === 0) continue
    out.push(`# ${elemName}`)
    for (const [attr, val] of pairs) {
      const type = ATTR_TYPES[attr] ?? 'String'
      if (type === 'Numeric') {
        out.push(`ElementAttrPutN(${val}, pDimension, pDimension, '${elemName}', '${attr}');`)
      } else {
        out.push(`ElementAttrPutS('${val}', pDimension, pDimension, '${elemName}', '${attr}');`)
      }
    }
  }
  return out.join('\n')
}

export function generateBuildDimensionSections(params, computed) {
  const { dimensionName } = params
  const { elements, edges, attributes } = computed

  const usedAttrs = new Set()
  for (const attrs of Object.values(attributes)) {
    for (const k of Object.keys(attrs)) usedAttrs.add(k)
  }

  return {
    prolog:   buildProlog(dimensionName, usedAttrs),
    metadata: buildMetadata(elements, edges),
    data:     '',
    epilog:   buildEpilog(attributes),
  }
}

export function generateBuildDimensionTI(params, computed) {
  const { prolog, metadata, epilog } = generateBuildDimensionSections(params, computed)
  return [
    `#####################################################`,
    `# BuildDimension — ${params.dimensionName}`,
    `# Generated by TM1 IDE Period Builder`,
    `#####################################################`,
    ``, `# ── PROLOG ──`, prolog,
    ``, `# ── METADATA ──`, metadata,
    ``, `# ── EPILOG (attribute values) ──`, epilog,
  ].join('\n')
}

// ── RefreshSubsets ────────────────────────────────────────────────────────────

function buildRefreshProlog(params, computed, selectedSubsets, subsetPrefix) {
  const { dimensionName, fyStartMonth } = params
  const { elements } = computed

  const pfx       = subsetPrefix ? subsetPrefix + ' ' : ''
  const leafMonths = elements.filter(e => e.type === 'N')
  const fyElements = elements.filter(e => e.level === 'fy')

  const needsCurrent = selectedSubsets.some(id => {
    const def = SUBSET_DEFS.find(d => d.id === id)
    return def?.requiresCurrent
  })

  const out = []
  out.push(`pDimension = '${dimensionName}';`)
  out.push(``)

  if (needsCurrent) {
    out.push(`sCurrentPeriod = '';`)
    out.push(`nCurrentSerial = 0;`)
    out.push(`sCurrentFY     = '';`)
    out.push(``)
    out.push(`vCount = DimSiz(pDimension);`)
    out.push(`vIdx = 1;`)
    out.push(`WHILE(vIdx <= vCount);`)
    out.push(`  sEl = DimNm(pDimension, vIdx);`)
    out.push(`  IF(ElementLevel(pDimension, pDimension, sEl) = 0);`)
    out.push(`    IF(ElementAttr(pDimension, 'Is Current Period', sEl) @= 'Y');`)
    out.push(`      sCurrentPeriod = sEl;`)
    out.push(`      nCurrentSerial = ElementAttr(pDimension, 'Period Start Serial', sEl);`)
    out.push(`      sCurrentFY     = ElementAttr(pDimension, 'Fin Year', sEl);`)
    out.push(`    ENDIF;`)
    out.push(`  ENDIF;`)
    out.push(`  vIdx = vIdx + 1;`)
    out.push(`END;`)
    out.push(``)
    out.push(`sPriorFY = '';`)
    out.push(`sNextFY  = '';`)
    out.push(`vPrevFY  = '';`)
    out.push(`vFoundFY = 0;`)
    out.push(`vIdx = 1;`)
    out.push(`WHILE(vIdx <= vCount);`)
    out.push(`  sEl = DimNm(pDimension, vIdx);`)
    out.push(`  IF(ElementLevel(pDimension, pDimension, sEl) > 0);`)
    out.push(`    IF(vFoundFY = 1 & sNextFY @= '');`)
    out.push(`      sNextFY = sEl;`)
    out.push(`    ENDIF;`)
    out.push(`    IF(sEl @= sCurrentFY);`)
    out.push(`      sPriorFY = vPrevFY;`)
    out.push(`      vFoundFY = 1;`)
    out.push(`    ENDIF;`)
    out.push(`    vPrevFY = sEl;`)
    out.push(`  ENDIF;`)
    out.push(`  vIdx = vIdx + 1;`)
    out.push(`END;`)
    out.push(``)

    if (selectedSubsets.includes('prior-ytd')) {
      out.push(`nFYStart = ${fyStartMonth};`)
      out.push(`nCurrentCalMonth  = ElementAttr(pDimension, 'Calendar Month', sCurrentPeriod);`)
      out.push(`nCurrentMonthInFY = MOD(nCurrentCalMonth - nFYStart + 12, 12) + 1;`)
      out.push(``)
    }
  }

  const writeStatic = (label, members) => {
    const name = pfx + label
    out.push(`# ${name}`)
    out.push(`IF(SubsetExists('${name}', pDimension) = 1);`)
    out.push(`  SubsetDestroy('${name}', pDimension);`)
    out.push(`ENDIF;`)
    out.push(`SubsetCreate('${name}', pDimension);`)
    members.forEach(({ name: el }, i) => {
      out.push(`SubsetElementInsert('${name}', pDimension, '${el}', ${i + 1});`)
    })
    out.push(``)
  }

  const writeDynamic = (label, condition) => {
    const name = pfx + label
    out.push(`# ${name}`)
    out.push(`IF(SubsetExists('${name}', pDimension) = 1);`)
    out.push(`  SubsetDestroy('${name}', pDimension);`)
    out.push(`ENDIF;`)
    out.push(`SubsetCreate('${name}', pDimension);`)
    out.push(`nPos = 1;`)
    out.push(`vIdx = 1;`)
    out.push(`WHILE(vIdx <= vCount);`)
    out.push(`  sEl = DimNm(pDimension, vIdx);`)
    out.push(`  IF(ElementLevel(pDimension, pDimension, sEl) = 0);`)
    out.push(`    IF(${condition});`)
    out.push(`      SubsetElementInsert('${name}', pDimension, sEl, nPos);`)
    out.push(`      nPos = nPos + 1;`)
    out.push(`    ENDIF;`)
    out.push(`  ENDIF;`)
    out.push(`  vIdx = vIdx + 1;`)
    out.push(`END;`)
    out.push(``)
  }

  for (const id of selectedSubsets) {
    switch (id) {
      case 'all-periods':
        writeStatic('All Periods', leafMonths); break
      case 'all-fy':
        writeStatic('All FY', fyElements); break
      case 'current-period':
        writeDynamic('Current Period', `ElementAttr(pDimension, 'Is Current Period', sEl) @= 'Y'`); break
      case 'prior-period':
        writeDynamic('Prior Period', `ElementAttr(pDimension, 'Next Period', sEl) @= sCurrentPeriod`); break
      case 'current-fy':
        writeDynamic('Current FY', `ElementAttr(pDimension, 'Fin Year', sEl) @= sCurrentFY`); break
      case 'prior-fy':
        writeDynamic('Prior FY', `ElementAttr(pDimension, 'Fin Year', sEl) @= sPriorFY`); break
      case 'next-fy':
        writeDynamic('Next FY', `ElementAttr(pDimension, 'Fin Year', sEl) @= sNextFY`); break
      case 'ytd':
        writeDynamic('YTD',
          `ElementAttr(pDimension, 'Fin Year', sEl) @= sCurrentFY & ElementAttr(pDimension, 'Period Start Serial', sEl) <= nCurrentSerial`); break
      case 'prior-ytd': {
        const name = pfx + 'Prior YTD'
        out.push(`# ${name}`)
        out.push(`IF(SubsetExists('${name}', pDimension) = 1);`)
        out.push(`  SubsetDestroy('${name}', pDimension);`)
        out.push(`ENDIF;`)
        out.push(`SubsetCreate('${name}', pDimension);`)
        out.push(`nPos = 1; vIdx = 1;`)
        out.push(`WHILE(vIdx <= vCount);`)
        out.push(`  sEl = DimNm(pDimension, vIdx);`)
        out.push(`  IF(ElementLevel(pDimension, pDimension, sEl) = 0);`)
        out.push(`    IF(ElementAttr(pDimension, 'Fin Year', sEl) @= sPriorFY);`)
        out.push(`      nElMonthInFY = MOD(ElementAttr(pDimension, 'Calendar Month', sEl) - nFYStart + 12, 12) + 1;`)
        out.push(`      IF(nElMonthInFY <= nCurrentMonthInFY);`)
        out.push(`        SubsetElementInsert('${name}', pDimension, sEl, nPos);`)
        out.push(`        nPos = nPos + 1;`)
        out.push(`      ENDIF;`)
        out.push(`    ENDIF;`)
        out.push(`  ENDIF;`)
        out.push(`  vIdx = vIdx + 1;`)
        out.push(`END;`)
        out.push(``)
        break
      }
      case 'rolling-12':
        writeDynamic('Rolling 12',
          `ElementAttr(pDimension, 'Period End Serial', sEl) <= nCurrentSerial & ElementAttr(pDimension, 'Period Start Serial', sEl) > nCurrentSerial - 367`); break
      case 'rolling-6':
        writeDynamic('Rolling 6',
          `ElementAttr(pDimension, 'Period End Serial', sEl) <= nCurrentSerial & ElementAttr(pDimension, 'Period Start Serial', sEl) > nCurrentSerial - 184`); break
      case 'rolling-3':
        writeDynamic('Rolling 3',
          `ElementAttr(pDimension, 'Period End Serial', sEl) <= nCurrentSerial & ElementAttr(pDimension, 'Period Start Serial', sEl) > nCurrentSerial - 93`); break
      case 'historical':
        writeDynamic('Historical', `ElementAttr(pDimension, 'Period End Serial', sEl) <= nCurrentSerial`); break
      case 'future':
        writeDynamic('Future', `ElementAttr(pDimension, 'Period Start Serial', sEl) > nCurrentSerial`); break
      case 'fy-remaining':
        writeDynamic('Current FY Remaining',
          `ElementAttr(pDimension, 'Fin Year', sEl) @= sCurrentFY & ElementAttr(pDimension, 'Period Start Serial', sEl) >= nCurrentSerial`); break
    }
  }

  return out.join('\n')
}

export function generateRefreshSubsetsSections(params, computed, selectedSubsets, subsetPrefix) {
  return {
    prolog:   buildRefreshProlog(params, computed, selectedSubsets, subsetPrefix),
    metadata: '',
    data:     '',
    epilog:   '',
  }
}

export function generateRefreshSubsetsTI(params, computed, selectedSubsets, subsetPrefix) {
  return [
    `#####################################################`,
    `# RefreshSubsets — ${params.dimensionName}`,
    `# Generated by TM1 IDE Period Builder`,
    `# Schedule: run monthly after Rollover TI`,
    `#####################################################`,
    ``,
    buildRefreshProlog(params, computed, selectedSubsets, subsetPrefix),
  ].join('\n')
}

// ── Rollover ──────────────────────────────────────────────────────────────────

function buildRolloverProlog(dimensionName) {
  const out = []
  out.push(`pDimension = '${dimensionName}';`)
  out.push(``)
  out.push(`# Find current period`)
  out.push(`sOldPeriod = '';`)
  out.push(`vCount = DimSiz(pDimension);`)
  out.push(`vIdx = 1;`)
  out.push(`WHILE(vIdx <= vCount);`)
  out.push(`  sEl = DimNm(pDimension, vIdx);`)
  out.push(`  IF(ElementLevel(pDimension, pDimension, sEl) = 0);`)
  out.push(`    IF(ElementAttr(pDimension, 'Is Current Period', sEl) @= 'Y');`)
  out.push(`      sOldPeriod = sEl;`)
  out.push(`    ENDIF;`)
  out.push(`  ENDIF;`)
  out.push(`  vIdx = vIdx + 1;`)
  out.push(`END;`)
  out.push(``)
  out.push(`# Determine new period — blank param = auto-advance by one month`)
  out.push(`IF(pPeriod @= '');`)
  out.push(`  sNewPeriod = ElementAttr(pDimension, 'Next Period', sOldPeriod);`)
  out.push(`ELSE;`)
  out.push(`  sNewPeriod = pPeriod;`)
  out.push(`ENDIF;`)
  out.push(``)
  out.push(`IF(sNewPeriod @= '');`)
  out.push(`  ProcessQuit;`)
  out.push(`ENDIF;`)
  out.push(``)
  out.push(`# Advance flag`)
  out.push(`IF(sOldPeriod @<> '');`)
  out.push(`  ElementAttrPutS('', pDimension, pDimension, sOldPeriod, 'Is Current Period');`)
  out.push(`ENDIF;`)
  out.push(`ElementAttrPutS('Y', pDimension, pDimension, sNewPeriod, 'Is Current Period');`)
  out.push(``)
  out.push(`# Rebuild all subsets`)
  out.push(`ExecuteProcess('${dimensionName}.RefreshSubsets');`)
  return out.join('\n')
}

export function generateRolloverSections(params) {
  return {
    prolog:   buildRolloverProlog(params.dimensionName),
    metadata: '',
    data:     '',
    epilog:   '',
    parameters: [
      {
        Name:   'pPeriod',
        Type:   'String',
        Value:  '',
        Prompt: 'Period to set as current (blank = auto-advance one month)',
      },
    ],
  }
}

export function generateRolloverTI(params) {
  return [
    `#####################################################`,
    `# Rollover — ${params.dimensionName}`,
    `# Generated by TM1 IDE Period Builder`,
    `# pPeriod: blank = advance one month, set = jump to specific period`,
    `# Schedule: monthly chore, 1st of month, pPeriod = ''`,
    `#####################################################`,
    ``,
    buildRolloverProlog(params.dimensionName),
  ].join('\n')
}
