import { SUBSET_DEFS } from './subsetDefs.js'
import {
  generateBuildDimensionProlog,
  generateBuildDimensionData,
  generateBuildDimensionEpilog,
} from './computeDimension.js'

export {
  generateBuildDimensionProlog,
  generateBuildDimensionData,
  generateBuildDimensionEpilog,
}

// ═══════════════════════════════════════════════════════════════════════
//  BUILD PERIOD DIMENSION TI
// ═══════════════════════════════════════════════════════════════════════

export function generateBuildDimensionSections(params, selectedSubsets = []) {
  return {
    prolog:   generateBuildDimensionProlog(params, selectedSubsets),
    metadata: '',
    data:     generateBuildDimensionData(params),
    epilog:   generateBuildDimensionEpilog(params, selectedSubsets),
    parameters: [
      { Name: 'pFirstFY',       Type: 'String', Value: params.firstFY,                  Prompt: 'First Fiscal Year (e.g. 2025)' },
      { Name: 'pLastFY',        Type: 'String', Value: params.lastFY,                   Prompt: 'Last Fiscal Year (e.g. 2035)' },
      { Name: 'pFYStartM',      Type: 'String', Value: params.fyStartMonth,             Prompt: 'FY start month (1-12)' },
      { Name: 'pCurrentPeriod', Type: 'String',  Value: params.defaultCurrentPeriod || '', Prompt: 'REQUIRED — Current period e.g. 2027-05' },
    ],
  }
}

export function generateBuildDimensionTI(params, selectedSubsets = []) {
  const prolog = generateBuildDimensionProlog(params, selectedSubsets)
  const data   = generateBuildDimensionData(params)
  const epilog = generateBuildDimensionEpilog(params, selectedSubsets)
  return [
    `#####################################################`,
    `# Build Period Dimension — ${params.dimensionName}`,
    `# Generated by TM1 IDE Period Builder`,
    `# Params: pFirstFY, pLastFY, pFYStartM, pCurrentPeriod`,
    `#####################################################`,
    ``,
    `# ── PROLOG ──`, prolog,
    ``,
    `# ── DATA ──`, data,
    ``,
    `# ── EPILOG ──`, epilog,
  ].join('\n')
}

// ═══════════════════════════════════════════════════════════════════════
//  REFRESH SUBSETS TI
// ═══════════════════════════════════════════════════════════════════════

function buildRefreshProlog(params, selectedSubsets, subsetPrefix) {
  const { dimensionName, fyStartMonth } = params
  const pfx = subsetPrefix ? subsetPrefix + ' ' : ''
  const needsCurrent = selectedSubsets.some(id => {
    const def = SUBSET_DEFS.find(d => d.id === id)
    return def?.requiresCurrent
  })

  const out = []

  out.push(`# ═══════════════════════════════════════════════════════════════`)
  out.push(`# Period Dimension Subset Rebuild`)
  out.push(`# ═══════════════════════════════════════════════════════════════`)
  out.push(`# Dimension: ${dimensionName}`)
  out.push(`# Purpose : Destroys and recreates all selected public subsets`)
  out.push(`# Input   : pCurrentPeriod — the month to use as reference`)
  out.push(`# Output  : Rebuild subsets in the target dimension`)
  out.push(`# ═══════════════════════════════════════════════════════════════`)
  out.push(``)
  out.push(`# ── Input: string working copies, numeric conversion ──`)
  out.push(`sDimension = pDimension;`)
  out.push(`sCurrentPeriod = pCurrentPeriod;`)
  out.push(`sMsg = '';`)
  out.push(`nFYStartM = NUMBR(TRIM(pFYStartM));`)
  out.push(``)
  out.push(`# ── Validate parameters ──`)
  out.push(`IF(DIMIX('}Dimensions', sDimension) = 0);`)
  out.push(`  sMsg = 'Dimension not found: ' | sDimension;`)
  out.push(`  AttrPutS('__ERROR:' | sMsg, '}Processes', GetProcessName(), '__RUN_LOG');`)
  out.push(`  ProcessQuit;`)
  out.push(`ENDIF;`)
  out.push(`nCount = DIMSIZ(sDimension);`)
  out.push(``)

  if (needsCurrent) {
    out.push(`# ─────────────────────────────────────────────`)
    out.push(`# Validate & Resolve Current Period`)
    out.push(`# ─────────────────────────────────────────────`)
    out.push(`IF(sCurrentPeriod @= '');`)
    out.push(`  sMsg = 'pCurrentPeriod is required — enter the current period e.g. 2027-05';`)
    out.push(`  AttrPutS(ATTRS('}Processes', GetProcessName(), '__RUN_LOG') | sMsg | CHAR(10), '}Processes', GetProcessName(), '__RUN_LOG');`)
    out.push(`  ProcessError;`)
    out.push(`ENDIF;`)
    out.push(`IF(DIMIX(sDimension, sCurrentPeriod) = 0);`)
    out.push(`  sMsg = 'pCurrentPeriod not found in dimension: ' | sCurrentPeriod;`)
    out.push(`  AttrPutS(ATTRS('}Processes', GetProcessName(), '__RUN_LOG') | sMsg | CHAR(10), '}Processes', GetProcessName(), '__RUN_LOG');`)
    out.push(`  ProcessError;`)
    out.push(`ENDIF;`)
    out.push(``)

    out.push(`# ── Read attribute values from current period element ──`)
    out.push(`# sCurrentFY = Fin Year of current period (e.g. 'FY2027')`)
    out.push(`sCurrentFY = ATTRS(sDimension, sCurrentPeriod, 'Fin Year');`)
    out.push(`# sPriorPeriod = month before current`)
    out.push(`sPriorPeriod = ATTRS(sDimension, sCurrentPeriod, 'Previous Period');`)
    out.push(`sYTD = ATTRS(sDimension, sCurrentPeriod, 'YTD');`)
    out.push(`sYTG = ATTRS(sDimension, sCurrentPeriod, 'YTG');`)
    out.push(`sLTD = ATTRS(sDimension, sCurrentPeriod, 'LTD');`)

    out.push(`# ── Extract FY year number and compute prior/next FY names ──`)
    out.push(`nFY = NUMBR(SUBST(sCurrentFY, 3, 4));`)
    out.push(`sPriorFY = 'FY' | NumberToString(nFY - 1);`)
    out.push(`sNextFY  = 'FY' | NumberToString(nFY + 1);`)
    out.push(`sOBL = NumberToString(nFY) | ' OBL';`)
    out.push(``)

    if (selectedSubsets.includes('prior-ytd') || selectedSubsets.includes('prior-ytg') || selectedSubsets.includes('prior-ltd')) {
      out.push(`# ─────────────────────────────────────────────`)
      out.push(`# Compute Prior-Year consolidation names`)
      out.push(`# ─────────────────────────────────────────────`)
      out.push(`nCalMonth = ATTRN(sDimension, sCurrentPeriod, 'Calendar Month');`)
      out.push(`nPriorFis = MOD(nCalMonth - nFYStartM + 12, 12) + 1;`)
      out.push(`sPriorYTD = 'YTD FY' | NumberToString(nFY - 1) | ' P' | IF(nPriorFis < 10, '0' | NumberToString(nPriorFis), NumberToString(nPriorFis));`)
      out.push(`sPriorYTG = 'YTG FY' | NumberToString(nFY - 1) | ' P' | IF(nPriorFis < 10, '0' | NumberToString(nPriorFis), NumberToString(nPriorFis));`)
      out.push(`sPriorLTD = 'LTD FY' | NumberToString(nFY - 1) | ' P' | IF(nPriorFis < 10, '0' | NumberToString(nPriorFis), NumberToString(nPriorFis));`)
      out.push(``)
    }
  }

  // Helper: create a public subset (destroy if exists)
  const writeSubset = (label) => {
    const name = pfx + label
    out.push(`# ══════ Subset: ${name} ══════`)
    out.push(`IF(SubsetExists(sDimension, '${name}') = 1);`)
    out.push(`  SubsetDestroy(sDimension, '${name}');`)
    out.push(`ENDIF;`)
    out.push(`SubsetCreate(sDimension, '${name}');`)
  }

  const addEl = (name, elExpr) => {
    out.push(`IF(DIMIX(sDimension, ${elExpr}) > 0);`)
    out.push(`  SubsetElementInsert(sDimension, '${name}', ${elExpr}, nPos);`)
    out.push(`  nPos = nPos + 1;`)
    out.push(`ENDIF;`)
  }

  const addChildren = (name, parentExpr) => {
    out.push(`IF(DIMIX(sDimension, ${parentExpr}) > 0);`)
    out.push(`  SubsetElementInsert(sDimension, '${name}', ${parentExpr}, nPos);`)
    out.push(`  nPos = nPos + 1;`)
    out.push(`  nChild = 1;`)
    out.push(`  nChildCount = ELCOMPN(sDimension, ${parentExpr});`)
    out.push(`  WHILE(nChild <= nChildCount);`)
    out.push(`    sChild = ELCOMP(sDimension, ${parentExpr}, nChild);`)
    out.push(`    SubsetElementInsert(sDimension, '${name}', sChild, nPos);`)
    out.push(`    nPos = nPos + 1;`)
    out.push(`    nChild = nChild + 1;`)
    out.push(`  END;`)
    out.push(`ENDIF;`)
  }

  for (const id of selectedSubsets) {
    const name = pfx + (() => {
      switch (id) {
        case 'all-periods':    return 'All Periods'
        case 'all-fy':         return 'All FY'
        case 'current-period': return 'Current Period'
        case 'prior-period':   return 'Prior Period'
        case 'current-fy':     return 'Current FY'
        case 'prior-fy':       return 'Prior FY'
        case 'next-fy':        return 'Next FY'
        case 'ytd':            return 'YTD'
        case 'ytg':            return 'YTG'
        case 'ltd':            return 'LTD'
        case 'prior-ytd':      return 'Prior YTD'
        case 'prior-ytg':      return 'Prior YTG'
        case 'prior-ltd':      return 'Prior LTD'
        case 'rolling-12':     return 'Rolling 12'
        case 'rolling-6':      return 'Rolling 6'
        case 'rolling-3':      return 'Rolling 3'
      }
    })()

    writeSubset(name)
    out.push(`nPos = 1;`)

    switch (id) {
      case 'all-periods':
        out.push(`# Walk entire dimension, include leaf elements (exclude OBL)`)
        out.push(`nIdx = 1;`)
        out.push(`WHILE(nIdx <= nCount);`)
        out.push(`  sEl = DIMNM(sDimension, nIdx);`)
        out.push(`  IF(ElementLevel(sDimension, sDimension, sEl) = 0);`)
        out.push(`    IF(ATTRS(sDimension, sEl, 'Period Type') @<> 'OBL');`)
        out.push(`      SubsetElementInsert(sDimension, '${name}', sEl, nPos);`)
        out.push(`      nPos = nPos + 1;`)
        out.push(`    ENDIF;`)
        out.push(`  ENDIF;`)
        out.push(`  nIdx = nIdx + 1;`)
        out.push(`END;`)
        break

      case 'all-fy':
        out.push(`# Walk dimension, include only FY consolidations`)
        out.push(`nIdx = 1;`)
        out.push(`WHILE(nIdx <= nCount);`)
        out.push(`  sEl = DIMNM(sDimension, nIdx);`)
        out.push(`  IF(ElementLevel(sDimension, sDimension, sEl) > 0);`)
        out.push(`    IF(SUBST(sEl, 1, 2) @= 'FY');`)
        out.push(`      SubsetElementInsert(sDimension, '${name}', sEl, nPos);`)
        out.push(`      nPos = nPos + 1;`)
        out.push(`    ENDIF;`)
        out.push(`  ENDIF;`)
        out.push(`  nIdx = nIdx + 1;`)
        out.push(`END;`)
        break

      case 'current-period':
        out.push(`# Single element: the current period`)
        addEl(name, `sCurrentPeriod`); break

      case 'prior-period':
        out.push(`# Single element: the period before current`)
        addEl(name, `sPriorPeriod`); break

      case 'current-fy':
        out.push(`# FY consolidation + all 12 months`)
        addChildren(name, `sCurrentFY`); break

      case 'prior-fy':
        out.push(`# Prior FY consolidation + all 12 months`)
        addChildren(name, `sPriorFY`); break

      case 'next-fy':
        out.push(`# Next FY consolidation + all 12 months`)
        addChildren(name, `sNextFY`); break

      case 'ytd':
        out.push(`# YTD consolidation + its children`)
        addChildren(name, `sYTD`); break

      case 'ytg':
        out.push(`# YTG consolidation + its children`)
        addChildren(name, `sYTG`); break

      case 'ltd':
        out.push(`# LTD = OBL + YTD consolidation + all month children`)
        out.push(`IF(DIMIX(sDimension, sLTD) > 0);`)
        out.push(`  SubsetElementInsert(sDimension, '${name}', sLTD, nPos);`)
        out.push(`  nPos = nPos + 1;`)
        out.push(`  nChild = 1;`)
        out.push(`  nChildCount = ELCOMPN(sDimension, sLTD);`)
        out.push(`  WHILE(nChild <= nChildCount);`)
        out.push(`    sChild = ELCOMP(sDimension, sLTD, nChild);`)
        out.push(`    SubsetElementInsert(sDimension, '${name}', sChild, nPos);`)
        out.push(`    nPos = nPos + 1;`)
        out.push(`    # For YTD child, also add its children (months)`)
        out.push(`    IF(sChild @<> sOBL);`)
        out.push(`      nGrand = 1;`)
        out.push(`      nGrandCount = ELCOMPN(sDimension, sChild);`)
        out.push(`      WHILE(nGrand <= nGrandCount);`)
        out.push(`        sGrand = ELCOMP(sDimension, sChild, nGrand);`)
        out.push(`        SubsetElementInsert(sDimension, '${name}', sGrand, nPos);`)
        out.push(`        nPos = nPos + 1;`)
        out.push(`        nGrand = nGrand + 1;`)
        out.push(`      END;`)
        out.push(`    ENDIF;`)
        out.push(`    nChild = nChild + 1;`)
        out.push(`  END;`)
        out.push(`ENDIF;`)
        break

      case 'prior-ytd':
        addChildren(name, `sPriorYTD`); break
      case 'prior-ytg':
        addChildren(name, `sPriorYTG`); break

      case 'prior-ltd':
        out.push(`# Prior LTD: same structure as LTD but for prior FY`)
        out.push(`sPriorOBL = NumberToString(nFY - 1) | ' OBL';`)
        out.push(`IF(DIMIX(sDimension, sPriorLTD) > 0);`)
        out.push(`  SubsetElementInsert(sDimension, '${name}', sPriorLTD, nPos);`)
        out.push(`  nPos = nPos + 1;`)
        out.push(`  nChild = 1;`)
        out.push(`  nChildCount = ELCOMPN(sDimension, sPriorLTD);`)
        out.push(`  WHILE(nChild <= nChildCount);`)
        out.push(`    sChild = ELCOMP(sDimension, sPriorLTD, nChild);`)
        out.push(`    SubsetElementInsert(sDimension, '${name}', sChild, nPos);`)
        out.push(`    nPos = nPos + 1;`)
        out.push(`    IF(sChild @<> sPriorOBL);`)
        out.push(`      nGrand = 1;`)
        out.push(`      nGrandCount = ELCOMPN(sDimension, sChild);`)
        out.push(`      WHILE(nGrand <= nGrandCount);`)
        out.push(`        sGrand = ELCOMP(sDimension, sChild, nGrand);`)
        out.push(`        SubsetElementInsert(sDimension, '${name}', sGrand, nPos);`)
        out.push(`        nPos = nPos + 1;`)
        out.push(`        nGrand = nGrand + 1;`)
        out.push(`      END;`)
        out.push(`    ENDIF;`)
        out.push(`    nChild = nChild + 1;`)
        out.push(`  END;`)
        out.push(`ENDIF;`)
        break

      case 'rolling-12':
        out.push(`# Rolling 12 subset`)
        addChildren(name, "'Rolling 12'"); break

      case 'rolling-6':
        out.push(`# Rolling 6 subset`)
        addChildren(name, "'Rolling 6'"); break

      case 'rolling-3':
        out.push(`# Rolling 3 subset`)
        addChildren(name, "'Rolling 3'"); break
    }
    out.push(``)
  }

  return out.join('\n')
}

export function generateRefreshSubsetsSections(params, selectedSubsets, subsetPrefix) {
  return {
    prolog:   buildRefreshProlog(params, selectedSubsets, subsetPrefix),
    metadata: '',
    data:     '',
    epilog:   '',
    parameters: [
      { Name: 'pDimension',     Type: 'String',  Value: params.dimensionName,              Prompt: 'Dimension name' },
      { Name: 'pCurrentPeriod', Type: 'String',  Value: params.defaultCurrentPeriod || '',  Prompt: 'REQUIRED — Current period e.g. 2027-05' },
      { Name: 'pFYStartM',      Type: 'String', Value: params.fyStartMonth,               Prompt: 'FY start month (1-12)' },
    ],
  }
}

export function generateRefreshSubsetsTI(params, selectedSubsets, subsetPrefix) {
  return [
    `#####################################################`,
    `# Refresh Subsets — ${params.dimensionName}`,
    `# Generated by TM1 IDE Period Builder`,
    `# Schedule: run monthly after Rollover TI`,
    `#####################################################`,
    ``,
    buildRefreshProlog(params, selectedSubsets, subsetPrefix),
  ].join('\n')
}

// ═══════════════════════════════════════════════════════════════════════
//  ROLLOVER TI
// ═══════════════════════════════════════════════════════════════════════

function buildRolloverProlog(dimensionName, fyStartMonth = 1) {
  const out = []
  out.push(`# ═══════════════════════════════════════════════════════════════`)
  out.push(`# ${dimensionName}.Rollover`)
  out.push(`#`)
  out.push(`# Purpose : Advances the 'Is Current Period' flag by one month`)
  out.push(`#           (or to any chosen period if pPeriod is supplied).`)
  out.push(`#           Automatically triggers .Refresh Subsets afterwards.`)
  out.push(`#`)
  out.push(`# Typical use: Monthly chore scheduled for the 1st of each month`)
  out.push(`#            with pPeriod left blank (auto-advance mode).`)
  out.push(`# ═══════════════════════════════════════════════════════════════`)
  out.push(``)
  out.push(`# ── Input: string working copies, numeric conversion ──`)
  out.push(`sDimension = pDimension;`)
  out.push(`sCurrentPeriod = pCurrentPeriod;`)
  out.push(`sPeriod = pPeriod;`)
  out.push(`sMsg = '';`)
  out.push(`nFYStartM = NUMBR(TRIM(pFYStartM));`)
  out.push(``)

  out.push(`# ─────────────────────────────────────────────`)
  out.push(`# 1. Validate input parameters`)
  out.push(`# ─────────────────────────────────────────────`)
  out.push(`IF(sCurrentPeriod @= '');`)
  out.push(`  sMsg = 'pCurrentPeriod is required — enter the current period e.g. 2027-05';`)
  out.push(`  AttrPutS('__ERROR:' | sMsg, '}Processes', GetProcessName(), '__RUN_LOG');`)
  out.push(`  ProcessQuit;`)
  out.push(`ENDIF;`)
  out.push(`IF(DIMIX(sDimension, sCurrentPeriod) = 0);`)
  out.push(`  sMsg = 'pCurrentPeriod not found in dimension: ' | sCurrentPeriod;`)
  out.push(`  AttrPutS('__ERROR:' | sMsg, '}Processes', GetProcessName(), '__RUN_LOG');`)
  out.push(`  ProcessQuit;`)
  out.push(`ENDIF;`)
  out.push(``)

  out.push(`# ─────────────────────────────────────────────`)
  out.push(`# 2. Advance Is Current Period flag`)
  out.push(`# sPeriod blank → auto-advance one month`)
  out.push(`# sPeriod set   → jump to specific period`)
  out.push(`# ─────────────────────────────────────────────`)
  out.push(`sOldPeriod = sCurrentPeriod;`)
  out.push(``)
  out.push(`IF(sPeriod @= '');`)
  out.push(`  sNewPeriod = ATTRS(sDimension, sOldPeriod, 'Next Period');`)
  out.push(`ELSE;`)
  out.push(`  sNewPeriod = sPeriod;`)
  out.push(`ENDIF;`)
  out.push(``)
  out.push(`IF(sNewPeriod @= '');`)
  out.push(`  ProcessQuit;`)
  out.push(`ENDIF;`)
  out.push(``)
  out.push(`# Clear old flag, set new flag`)
  out.push(`IF(sOldPeriod @<> '');`)
  out.push(`  AttrPutS('', sDimension, sOldPeriod, 'Is Current Period');`)
  out.push(`ENDIF;`)
  out.push(`AttrPutS('Y', sDimension, sNewPeriod, 'Is Current Period');`)
  out.push(``)
  out.push(`# Rebuild subsets using new current period`)
  out.push(`IF(sOldPeriod @<> '');`)
  out.push(`  ExecuteProcess(sDimension | '.Refresh Subsets',`)
  out.push(`                 'pCurrentPeriod', sNewPeriod,`)
  out.push(`                 'pFYStartM', NumberToString(nFYStartM));`)
  out.push(`ENDIF;`)
  return out.join('\n')
}

export function generateRolloverSections(params) {
  return {
    prolog:   buildRolloverProlog(params.dimensionName, params.fyStartMonth),
    metadata: '',
    data:     '',
    epilog:   '',
    parameters: [
      { Name: 'pDimension',     Type: 'String',  Value: params.dimensionName,              Prompt: 'Dimension name' },
      { Name: 'pCurrentPeriod', Type: 'String',  Value: params.defaultCurrentPeriod || '',  Prompt: 'REQUIRED — Current period e.g. 2027-05' },
      { Name: 'pPeriod',        Type: 'String',  Value: '',                                 Prompt: 'Period to set as current (blank = auto-advance)' },
      { Name: 'pFYStartM',      Type: 'String', Value: params.fyStartMonth,               Prompt: 'FY start month (1-12) — passed to Refresh Subsets' },
    ],
  }
}

export function generateRolloverTI(params) {
  return [
    `#####################################################`,
    `# ${params.dimensionName}.Rollover`,
    `# Generated by TM1 IDE Period Builder`,
    `#`,
    `# Purpose : Advances the 'Is Current Period' flag by one month`,
    `#           (or to a specific period if pPeriod is supplied).`,
    `#           Then triggers .Refresh Subsets for the new current period.`,
    `#`,
    `# Parameters:`,
    `#   pCurrentPeriod  (required) — Current period element name (e.g. 2027-05)`,
    `#   pPeriod         (optional) — Target period. Blank = auto-advance`,
    `#   pFYStartM       (optional) — Fiscal year start month`,
    `#`,
    `# Recommended schedule: Monthly chore on the 1st of each month`,
    `#####################################################`,
    ``,
    buildRolloverProlog(params.dimensionName, params.fyStartMonth),
  ].join('\n')
}
