export const SUBSET_DEFS = [
  { id: 'all-periods',    label: 'All Periods',   requiresCurrent: false, defaultOn: true  },
  { id: 'all-fy',         label: 'All FY',        requiresCurrent: false, defaultOn: true  },
  { id: 'current-period', label: 'Current Period', requiresCurrent: true,  defaultOn: true  },
  { id: 'prior-period',   label: 'Prior Period',  requiresCurrent: true,  defaultOn: false },
  { id: 'current-fy',     label: 'Current FY',    requiresCurrent: true,  defaultOn: true  },
  { id: 'prior-fy',       label: 'Prior FY',      requiresCurrent: true,  defaultOn: true  },
  { id: 'next-fy',        label: 'Next FY',       requiresCurrent: true,  defaultOn: false },
  { id: 'ytd',            label: 'YTD',           requiresCurrent: true,  defaultOn: true  },
  { id: 'ytg',            label: 'YTG',           requiresCurrent: true,  defaultOn: true  },
  { id: 'ltd',            label: 'LTD',           requiresCurrent: true,  defaultOn: true  },
  { id: 'prior-ytd',      label: 'Prior YTD',     requiresCurrent: true,  defaultOn: false },
  { id: 'prior-ytg',      label: 'Prior YTG',     requiresCurrent: true,  defaultOn: false },
  { id: 'prior-ltd',      label: 'Prior LTD',     requiresCurrent: true,  defaultOn: false },
  { id: 'rolling-12',     label: 'Rolling 12',    requiresCurrent: true,  defaultOn: false },
  { id: 'rolling-6',      label: 'Rolling 6',     requiresCurrent: true,  defaultOn: false },
  { id: 'rolling-3',      label: 'Rolling 3',     requiresCurrent: true,  defaultOn: false },
]
